# src/main/resources/application.yml
spring:
  cache:
    enabled: true
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2s
    cache:
      # global default TTL for caches (0 = no expiry)
      timeToLive: 5m
      usePrefix: true
      # prefix resolves to "<appName>:<profile>:" e.g., "ordersvc:prod:"
      keyPrefix: ${spring.application.name:${random.value}}:${spring.profiles.active:default}:
      allowNullValues: false
      transactionAware: false
      cacheExpirations: { }  # per-cache overrides go in the app that consumes this
